name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

# 顶层变量（但不能由环境继承，必须为每个环境指定）
#[vars]
#CUSTOM_DOMAIN = "grit.us.kg"

# production 环境变量，不能继承顶层 vars
[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
# 改为在 Github repository -> Settings -> Secrets and variables -> Actions -> Repository secrets 中添加 CUSTOM_DOMAIN，具体参考 .github/workflows/deploy.yaml 文件
#CUSTOM_DOMAIN = "grit.us.kg"

[env.production]
routes = [
  { pattern = "hub.grit.us.kg", custom_domain = true },
  { pattern = "docker.grit.us.kg", custom_domain = true },
  { pattern = "quay.grit.us.kg", custom_domain = true },
  { pattern = "gcr.grit.us.kg", custom_domain = true },
  { pattern = "k8s-gcr.grit.us.kg", custom_domain = true },
  { pattern = "k8s.grit.us.kg", custom_domain = true },
  { pattern = "ghcr.grit.us.kg", custom_domain = true },
  { pattern = "cloudsmith.grit.us.kg", custom_domain = true },
  { pattern = "ecr.grit.us.kg", custom_domain = true },
  { pattern = "mcr.grit.us.kg", custom_domain = true },
  { pattern = "elastic.grit.us.kg", custom_domain = true },
  { pattern = "nvcr.grit.us.kg", custom_domain = true },
  { pattern = "juju.grit.us.kg", custom_domain = true },
  { pattern = "l5d.grit.us.kg", custom_domain = true },
  { pattern = "rocks.grit.us.kg", custom_domain = true },
]

# staging 环境变量
[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
#CUSTOM_DOMAIN = "grit.us.kg"

[env.staging]
route = { pattern = "docker-staging.grit.us.kg", custom_domain = true }

# dev 环境变量
[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
#CUSTOM_DOMAIN = "grit.us.kg"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
